com: 
  zipkin:
    serviceName: ENHANCE-ZIPKIN-PROD
    url:  http://127.0.0.1:9411/api/v2/spans
    connectTimeout: 10000
    readTimeout: 1000
    flushInterval: 1000
    compressionEnabled: true
    endpoint: http://127.0.0.1:9411/api/v2/spans
# 端口信息
server:
  port: 20002
# 应用名称
spring:
  application:
    name: ENHANCE-ZIPKIN-PROD
  profiles:
    active: prod
# 数据库的连接信息
# 日志级别
logging:
  level:
    key : info
  config: classpath:logback-spring.xml


eureka:
  client:
    serviceUrl:
      defaultZone:  http://eureka-server-01:7001/eureka/
